###############################################################
# Program:
#     Assignment 09, Binary Search Tree
#     Brother Kirby, CS235
# Author:
#     Andres Rodriguez, Pedro Bastos, Fangyi Li
# Summary:
#      This programming assignment will be to create the binary 
#      tree data structure and use it to implement a program 
#      to generate Huffman codes
# Coding Time:
#     Pair Programming: 1.5 hours
#     Andres: XX hours 
#     Pedro:  XX hours
#     Fangyi: XX hours
#
# The most difficult part:
#       Andres: 
#       Pedro: 
#       Fangyi: 
###############################################################


##############################################################
# The main rule
##############################################################
a.out: assignment09.o
	g++ -o a.out assignment09.o -std=c++11
	tar -cf assignment09.tar *.h *.cpp makefile

##############################################################
# The individual components
#      assignment09.o     : the driver program
##############################################################
assignment09.o: bst.h assignment09.cpp
	g++ -c assignment09.cpp -std=c++11

